### ISSUE TITLE
Dashboard screen

### ISSUE THREAD

**Issue by oferitz** [rethinkdb/rethinkdb-desktop#9]
1. The dashboard screen is the default view after successful connection and is the fallback view for any unknown routing attempt.

components:
1.  Status bar:
- Servers 
     N server connected
     N servers missing
- Tables
     N tables ready
     N tables with issues
- Indexes
      N secondary indexes
      N indexes building
- Resources
     X% cache used
     X Bytes disk used

![image](https://user-images.githubusercontent.com/1857466/40423572-adf3b330-5e9b-11e8-981b-573c1491f245.png)

Cluster performance: Dynamic line chart (should be good react component that support smart dynamic updates without re-rendering the whole component.

![image](https://user-images.githubusercontent.com/1857466/40423585-b858bcbc-5e9b-11e8-93d4-50dbd1473a7a.png)

Recent log entries component.

![image](https://user-images.githubusercontent.com/1857466/40423599-c36290a6-5e9b-11e8-82eb-d9890b186c94.png)

**Comment by sagivf** [comment]
@oferitz Just a quick FYI - i'm working on this along with the dashboard page.
Here is the branch - https://github.com/RebirthDB/rebirthdb-desktop/tree/%239%26%237-dashboard-page-and-info-panel
I estimate to get these both to full completion - data, chart, UI, will take me about 3-4 weeks.

**Comment by oferitz** [comment]
@sagivf We need to merge #34 before you start working on it, it contains major changes based on your previous work and we will have a lot of conflicts if we don't do so.

**Comment by sagivf** [comment]
I had a look, looks great, no problem, I will rebase on to it once it's merged, What's missing in getting it rebased?

**Comment by oferitz** [comment]
Writing some tests, should be ready soon

**Comment by ghiscoding** [comment]
@oferitz @thelinuxlich 
For the live graph part, I know `highchart` was discussed in the forum (and excluded because of their license) but have you guys ever considered [Chart.JS](https://www.chartjs.org), it is so much better and has an amazing look and feel that is really hard to beat. Event Bootstrap 4 added it in their [dashboard demo](https://bootstrap-themes.github.io/dashboard/fluid/index.html). Their license is MIT so I guess it would be fine to use here.

Their implementation is quite easy, you give it an array of data and it creates the graph dynamically (with a visual effect). If you keep pushing data to it, it will readjust the graph, so you can simulate a live graph like in the old RethinkDB admin Cluster Performance. Check the [line graph](http://www.chartjs.org/samples/latest/scales/logarithmic/line.html) demo and click on the randomize data button.

Note, I didn't want to create a new account on the forum just to post this comment. So I posted here.

**Comment by oferitz** [comment]
@ghiscoding Chart.js looks great indeed and if it fits our needs we should definitely try it. @sagivf lets give it a try.

**Comment by sagivf** [comment]
My past experience has always been to fallback to `highcharts`, but it's been a while since i've done charts. I'm getting to this soon(been busy for the past 2 weeks), i'll let you know how it goes,

**Comment by PierreAndreis** [comment]
What about https://github.com/FormidableLabs/victory-chart ?

**Comment by oferitz** [comment]
@PierreAndreis Any chart lib that follow:

a. Maintainable and has decent number of users
b. Has easy React integration
c. Can render dynamic data while playing nicely with React components lifecycle

Is a legit choice. if Victory falls into this and we have a hero that want to implement it (for example in #19) then he/she are more than welcome to do so.

**Comment by sagivf** [comment]
@oferitz @PierreAndreis added a pull request of the cluster time series chart with `victory-charts`.
Needs a little more fine tuning, but I think it's OK.

I have to say, victory-charts seems pretty powerful, but it's documentation and examples are hard to use.
Basic stuff like sizing and formatting was pretty hard to figure out.

**Comment by sagivf** [comment]
Lets open issues for the small issues and improvements needed
